version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_rental
    environment:
      POSTGRES_DB: rental
      POSTGRES_USER: gestion
      POSTGRES_PASSWORD: gestion123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    restart: always

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
